// Mocks generated by Mockito 5.4.6 from annotations
// in how_i_like_my_coffee/test/features/coffee_reccommender/domain/usecases/get_recommendation_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:how_i_like_my_coffee/core/error/failure.dart' as _i5;
import 'package:how_i_like_my_coffee/features/coffee_reccommender/domain/entities/coffee_profile_entity.dart'
    as _i6;
import 'package:how_i_like_my_coffee/features/coffee_reccommender/domain/entities/dictionary_entry_entity.dart'
    as _i7;
import 'package:how_i_like_my_coffee/features/coffee_reccommender/domain/repositories/coffee_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CoffeeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoffeeRepository extends _i1.Mock implements _i3.CoffeeRepository {
  MockCoffeeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CoffeeProfileEntity>>>
      getRecommendation({
    required String? temperature,
    required String? body,
    required List<String>? aromas,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getRecommendation,
              [],
              {
                #temperature: temperature,
                #body: body,
                #aromas: aromas,
              },
            ),
            returnValue: _i4.Future<
                    _i2
                    .Either<_i5.Failure, List<_i6.CoffeeProfileEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CoffeeProfileEntity>>(
              this,
              Invocation.method(
                #getRecommendation,
                [],
                {
                  #temperature: temperature,
                  #body: body,
                  #aromas: aromas,
                },
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.CoffeeProfileEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.DictionaryEntryEntity>>>
      getDictionaryEntries() => (super.noSuchMethod(
            Invocation.method(
              #getDictionaryEntries,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure,
                        List<_i7.DictionaryEntryEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.DictionaryEntryEntity>>(
              this,
              Invocation.method(
                #getDictionaryEntries,
                [],
              ),
            )),
          ) as _i4.Future<
              _i2.Either<_i5.Failure, List<_i7.DictionaryEntryEntity>>>);
}
